version: "3.9"
services:
  personapi:
    build: .
    ports:
      - "8000:8000"
    environment:
      PERSONAPI_DB_CONN_STR: mongodb://persondb:27017/
      PERSONAPI_SIMULATED_DELAY_SECONDS:
      PERSONAPI_AUTH_TOKEN_BASE_SECRET:
      PERSONAPI_AUTH_TOKEN_EXPIRATION_IN_MINUTES:
      PERSONAPI_AUTH_TOKEN_ALGORITHM:
  persondb:
    image: mongo
    ports:
      - "27017:27017"
