FROM python:3.9-alpine

EXPOSE 8000/tcp
ENV NEW_RELIC_CONFIG_FILE=newrelic.ini

# About requirements.tx:
# - It must be generated by pipenv before building.
# - It must NOT contain the local app package, so we can install it before
#   copying the app's source.
# - See Makefile.
#
# That way when we change the app's code, the image build is faster, because the
# layer that installed the requirements is not rebuilt.

COPY requirements.txt /app/
WORKDIR /app
RUN pip install -r requirements.txt
COPY newrelic.ini /app
COPY setup.py /app/
COPY src /app/src
RUN pip install .
CMD newrelic-admin run-program uvicorn --host 0.0.0.0 personapi.api:app