version: "3.9" 
services:
  python-person-api:
    build: ./python-person-api
    ports:
      - "8000:8000"
    environment:
      DB_CONN_STR: mongodb://person-db:27017/
  person-db:
    build: ./person-db
    ports:
      - "27017:27017"
