version: "3.9"
services:
  personapi:
    build: .
    ports:
      - "8000:8000"
    environment:
      DB_CONN_STR: mongodb://persondb:27017/
      SIMULATED_DELAY_SECONDS:
  persondb:
    image: mongo
    ports:
      - "27017:27017"
