FROM python:3.9-alpine

EXPOSE 8000/tcp
ENV NEW_RELIC_CONFIG_FILE=newrelic.ini

# requirements.txt must be generated by pipenv before building. See Makefile.
COPY requirements.txt /app/
COPY setup.py /app/
COPY src /app/src
WORKDIR /app
RUN pip install -r requirements.txt
COPY newrelic.ini /app
CMD newrelic-admin run-program uvicorn --host 0.0.0.0 personapi.api:app