FROM python:3.9-alpine AS python-builder

EXPOSE 8000/tcp
ENV NEW_RELIC_CONFIG_FILE=newrelic.ini


RUN apk add build-base
RUN apk add libffi-dev

RUN adduser -D personapi
USER personapi

# About requirements.tx:
# - It must be generated by pipenv before building.
# - It must NOT contain the local app package, so we can install it before
#   copying the app's source.
# - See Makefile.
#
# That way when we change the app's code, the image build is faster, because the
# layer that installed the requirements is not rebuilt.

COPY requirements.txt /tmp/
RUN pip install --user -r /tmp/requirements.txt

##### second stage

FROM python:3.9-alpine AS python-runner

RUN adduser -D personapi
USER personapi

ENV PATH="/home/personapi/.local/bin:${PATH}"

COPY --from=0 /home/personapi/.local /home/personapi/.local
WORKDIR /app
COPY newrelic.ini /app
COPY setup.py /app/
COPY src /app/src
RUN pip install .
# CMD newrelic-admin run-program uvicorn --host 0.0.0.0 personapi.api:app
CMD uvicorn --host 0.0.0.0 personapi.api:app