apiVersion: v1
kind: Pod
metadata:
  name: python-person-api-1
spec:
  containers:
  - name: python-person-api-1
    image: python-person-api/person-api:v0.9.1
    ports:
    - containerPort: 8000
---
apiVersion: v1
kind: Pod
metadata:
  name: python-person-api-2
spec:
  containers:
  - name: python-person-api-2
    image: docker.io/python-person-api/person-api:v0.9.1
    ports:
    - containerPort: 8000
